version: '3.9'

networks:
 khem_network:

services:
  app:
    build: .docker/php
    container_name: app_khemerak
    volumes:
      - .:/var/www
    ports:
      - 9000
    command: ["sh", "-c", "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && chmod -R 775 /var/www/storage /var/www/bootstrap/cache && php-fpm"]
  nginx:
    image: nginx
    depends_on:
      - app
    container_name: nginx_khem
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
     - khem_network

  db:
    image: postgres:16
    container_name: db
    ports:
      - 5433:5432
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_khemerak
    networks:
     - khem_network
