version: '3.7'
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: edf_backend
    container_name: edf_backend_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - edf_backend_app
#  db:
#    image: postgres:15
#    container_name: postgres-db
#    restart: always
#    environment:
#      POSTGRES_DB: edf_service
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root2022
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    networks:
#      - edf_backend_app
#    ports:
#      - "54321:5432"
  nginx:
    image: nginx:stable
    container_name: edf_gov_kh_nginx
    restart: unless-stopped
    ports:
      - 9090:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - edf_backend_app

#volumes:
#  db_data:
networks:
  edf_backend_app:
    driver: bridge
