version: '3.9'

#networks:
#  edf_app:
#    name: edf_app

services:
  app:
    build: .docker/php
    #    container_name: app
    volumes:
      - .:/var/www
    ports:
      - 9000
  nginx:
    image: nginx
    depends_on:
      - app
#    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - edf_app

  db:
    image: postgres:16
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=edf_C0ntr0l
      - POSTGRES_DB=edf_service
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www
    working_dir: /var/www
#    networks:
#      - edf_app
  npm:
    image: node:current-alpine
    container_name: npm
    volumes:
      - .:/var/www
    working_dir: /var/www
    entrypoint: ['npm']
#    networks:
#      - edf_app
